<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>SharpSite.Plugins.SharpShop</AssemblyName>
    <RootNamespace>SharpSite.Plugins.SharpShop</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\SharpSite.Abstractions.Base\SharpSite.Abstractions.Base.csproj" />
  </ItemGroup>

</Project>